### ISSUE TITLE
Wrong calculation of some holidays concerning eastern

### ISSUE THREAD

**Issue by bilobait-balleyer** [micronax/carbon-german-holidays#4]
`Line 121: $easter = self::createFromDate($year, 03, 21);`
needs `startOfDay()` because of `in_array()` check in line 94
`Line 121: $easter = self::createFromDate($year, 03, 21)->startOfDay();`

`Line 137: $easterSunday = self::getEasterSunday($year)->format(u);`
returns on Debian system a 1970 year and crashes all further eastern time calculations. Change it to

`Line 137: $easterSunday = self::getEasterSunday($year)->timestamp;`
because of Carbon correct timestamp method

**Comment by bilobait-balleyer** [comment]
Or more easier combine both fixes in Line 137:
`Line 137: $easterSunday = self::getEasterSunday($year)->startOfDay()->timestamp;`

**Comment by micronax** [comment]
Hi @bilobait-balleyer! Thank you for those lines of code. May I ask you to create a pull request with those changes? THX

**Comment by bilobait-balleyer** [comment]
@micronax 

Done. This was my first pull request. I hope i have done it the correct way ;-)

**Comment by micronax** [comment]
I am sorry but didn't receive any pull request. Could you check again?

**Comment by bilobait-balleyer** [comment]
Yes you are right. Have someone deleted it? Someone added the timestamp() method but the missing startoftheday() at the eastern calculation is still missing. In my opinion the in_array() method will not detect all of the eastern days because of this bug.
