### ISSUE TITLE
Easter doesn't show up

### ISSUE THREAD

**Issue by tmdevde** [micronax/carbon-german-holidays#6]
Hi there,

thank you for this brilliant package! It is working fine but eastern doesn't show up for any year in the checks with isGermanHoliday() for me. Everything else does. I'm currently on Version 2.1.

`CarbonGermanHolidays::createFromDate(2022, 04, 17)->isGermanHoliday(CarbonGermanHolidays::ALL_STATES_ALL_DAYS)`
`CarbonGermanHolidays::createFromDate(2022, 04, 15)->isGermanHoliday(CarbonGermanHolidays::ALL_STATES_ALL_DAYS)`

**Comment by micronax** [comment]
Hi there, please try again with the latest 2.2. version

**Comment by tmdevde** [comment]
Perfect! Thank you for the fast response!
