### ISSUE TITLE
Deprecated: Use of "self" in callables is deprecated

### ISSUE THREAD

**Issue by hija** [micronax/carbon-german-holidays#9]
Hello,

when using the library, I get the notification that [the use of self in callables is deprecated](https://php.watch/versions/8.2/partially-supported-callable-deprecation) in the following line:

https://github.com/micronax/carbon-german-holidays/blob/dfd325d816a2cb6887eb6f007f8936b2f4345edf/src/Fgits/CarbonGermanHolidays/CarbonGermanHolidays.php#L233

One fix would be to change it to

`
        return array_map(self::class . '::unix2Date', $holidays);
`

However, since I am not very experienced with PHP I do not know if this is best practice or not.

Maybe someone can guide me into the right direction so that I can create a PR to fix the deprecation?

Best
Hilko

**Comment by micronax** [comment]
Hi Hilko, thank you! I will have a look into this later this week.

**Comment by micronax** [comment]
Addressed and fixed in https://github.com/micronax/carbon-german-holidays/commit/f48fd169c38a51c425904b80e88c612f9759927f

**Comment by hija** [comment]
Nice, thank you 👍
